# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "VpvY9ldL5Zq77Virf2i9X3LiLldHfZtXE4QI4by1iFl0R0u1dtLvGTzhkGO8Bfo2I/qYv3/hHQvuosFPetIix4q/6v7b4ycIqzBA5/7CodXwxokuijSrvcLwH+V/UeN9CbTvIsKlAIeI+vjViimH3YEdgKJ81iC+EsPedVVGNgnMqSdDCOK+JEF0157pbX6JVrwoyQiJ411hxaB0tJ8AEvAqRRa2TpVfcnHV7rhW2bSsZ8uydUV/rTKi4EHQp+oKKgWJUIhJWO98HSQoittcQSDqLE97aT+kuC/nGTeKUIrg/rTfxM5yPjFM4Cnx48UzSXIe4h7mBSgk6Qe4kfpwqQbLa9DEaK9t+4QVjK4pDbJhQpz8DJGJL8RCOtg/ccPydHwxKU7Ky7xFRqCM0v4sQB5/iZwDn4vPO8a6Qz20jodJ1idcWBXD+O9C2Zk8CcdmC7fahzODjbKp8Mm+zQxBiHDMcTxOaHTXq8F/4zWk3tX7wdAb6lPiPlVuawJWhWxNLbshmL3hKxOJ133iuf2m1k9/PqERn9JRvrTHeeyimbqVjhe59dnoN7nBLE4ic4v3HRWQI0J3mo7z3eLZcfxA9zcnQnzF4zzk9hojDEbw15D57eF5BVsqKxv70DkZpY+AZarIwn+A1gu8yB5+vcMz7XBAzcqqo3DJ9CKTfVbxmIY="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
