travis:
  secure:
    BINSTAR_TOKEN: GqWFxF64FVUNFkzdroO5P0e2WG5S67ROJO6QdPcSMr0WBdCRYNBqDK51bc15gxy+54uLbYsNuJtxxqMP4J6aYQ+83NOj5OZXldFBYWEWg+bIJyI3nTkib42bpG10/FDNTt/rd6/jPbzr2yiLR0PhtKC6GVmQKNVj8At/8Q73ZOVQg34thGL/7aqyC7KgCHMkAIToVMXWn9z201eU3T1FTxEd+3Hc/kkbjzkRwdB3BPjTyX8Z2MYNQfuDa9Sp97kOJpx1iTlua/3tAPIAFBOfMO+VFBOLRmr6Qgu9dE+tpIHEtOQ8H1LuqxrdB9jumLXtRv3MRx715qLl2rhPaWyabfnoKrP6Uvh7lp0oEA/DdtqV9Q0itwabkDD++vBE4BEbirzAwx55W4h6Ea2eGCiKDk66zOfW6qU98VLSIpDt0Z/rsCk0n0MQX11RNE3Cjs32eD1xGvL2odaLuPPKp3gq4IGXDxmANkCE5TCBSLmGv4PiXlz5ecBhAGmn77V2/8K+IFKR++68IfSkUeklcCH/8R3NVuvCayu71L9iAxo8Mx/OS1jIj2uZXlZNHgyVDisiKPRAQAgJ1S0Nae/S8YuxQdtMNs/3Iogmrrb/ya+0su86tUIIu3GcIuhwIrYwN+ZXhqsIG+KqvZE0kNMM5iHFQZbdNFy2ZlTBBALUXK2d72w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
