travis:
  secure:
    BINSTAR_TOKEN: IQitNyifpeXeLdjbEK8AlGSQ8BqAZ7IP3xqNpIiqZKmtAWwf9Wdh14g87w3rvN445v4jcoBb7rUKSsCsDFplSpHckM8j11y2hXqEKzI4tNgVS6ShcDSAGCdINcrCz9dGuNYrLcUFJXvrBfkb7Z897ttpNfQgNVV8BqXXy5mVcJHTWfch9+2CUtKIzUWTSy9KtLd2EWT5rY0ENC96lD/I8E2ToyRkMf6zdMCsKJlIqyZOA/ZrxtN3tTVDcLh3xkU0uOZl2LiNdJ2r75ySHL0r8yF9SuAwvDoiB/7PfkLIjCUlZ4WpfrXcLq9Sudkx4RDusyGFyvjDi9uPkN6YVplZ+aLUNGtwSYf7SFyPviDAiZfH1VFK/+sY8IOQhviSydwKD5yHQU/PKkunGzr2jWxPTZWDvB8hTPNRETUXFDyKp/4+8isOQ3Ij0YUJ/sB3yP83Z0Vxwxnh8ZK7cSjFtxbqwJnlgAf7nX4Oimq1p++3OWOza1RGq1veuHC4BaEC5E+Ogwk8gJqYG3KuJE/p20MZobmUgxnOYPip8tooRp8M5An5WtgF/WwN1QEpZqFJNMBVBg5h0Vn4Hrbp9xqVAPae40Fs9NZp48UPpOjl+leuM+29PpbvQPzpDE8qsDutLSuUwJ7YGZ+yex5/OUEPprUyU33oojHesyYmJQHrIrR2apA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
